# Named Entityy Recogninatoion

In [1]:
import spacy
from nltk import sent_tokenize

In [2]:
!python -m spacy download en_core_web_trf

Collecting en-core-web-trf==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.8.0/en_core_web_trf-3.8.0-py3-none-any.whl (457.4 MB)
     ---------------------------------------- 0.0/457.4 MB ? eta -:--:--
     ---------------------------------------- 0.3/457.4 MB ? eta -:--:--
     ---------------------------------------- 1.0/457.4 MB 2.8 MB/s eta 0:02:44
     ---------------------------------------- 1.8/457.4 MB 3.2 MB/s eta 0:02:21
     ---------------------------------------- 2.6/457.4 MB 3.5 MB/s eta 0:02:10
     ---------------------------------------- 3.4/457.4 MB 3.7 MB/s eta 0:02:02
     ---------------------------------------- 4.5/457.4 MB 3.7 MB/s eta 0:02:02
     ---------------------------------------- 5.0/457.4 MB 3.5 MB/s eta 0:02:09
     ---------------------------------------- 5.5/457.4 MB 3.4 MB/s eta 0:02:12
      --------------------------------------- 6.3/457.4 MB 3.4 MB/s eta 0:02:13
      --------------------------------------- 6.8/457.4 MB 3.3 MB/s eta 0:02:17
      --------------------------------------- 7.6/457.4 MB 3.4 MB/s eta 0:02:13
      --------------------------------------- 8.4/457.4 MB 3.4 MB/s eta 0:02:11
      --------------------------------------- 9.4/457.4 MB 3.5 MB/s eta 0:02:07
      -------------------------------------- 10.2/457.4 MB 3.6 MB/s eta 0:02:06
      -------------------------------------- 11.0/457.4 MB 3.6 MB/s eta 0:02:04
     - ------------------------------------- 11.8/457.4 MB 3.6 MB/s eta 0:02:04
     - ------------------------------------- 12.8/457.4 MB 3.7 MB/s eta 0:02:02
     - ------------------------------------- 13.9/457.4 MB 3.7 MB/s eta 0:01:59
     - ------------------------------------- 14.7/457.4 MB 3.8 MB/s eta 0:01:59
     - ------------------------------------- 15.5/457.4 MB 3.8 MB/s eta 0:01:58
     - ------------------------------------- 16.0/457.4 MB 3.8 MB/s eta 0:01:58
     - ------------------------------------- 16.8/457.4 MB 3.7 MB/s eta 0:02:01
     - ------------------------------------- 16.8/457.4 MB 3.7 MB/s eta 0:02:01
     - ------------------------------------- 17.3/457.4 MB 3.5 MB/s eta 0:02:07
     - ------------------------------------- 17.8/457.4 MB 3.4 MB/s eta 0:02:08
     - ------------------------------------- 18.6/457.4 MB 3.4 MB/s eta 0:02:09
     - ------------------------------------- 19.1/457.4 MB 3.4 MB/s eta 0:02:08
     - ------------------------------------- 19.9/457.4 MB 3.4 MB/s eta 0:02:09
     - ------------------------------------- 20.4/457.4 MB 3.4 MB/s eta 0:02:10
     - ------------------------------------- 21.2/457.4 MB 3.4 MB/s eta 0:02:09
     - ------------------------------------- 21.5/457.4 MB 3.4 MB/s eta 0:02:10
     - ------------------------------------- 21.8/457.4 MB 3.3 MB/s eta 0:02:11
     - ------------------------------------- 22.5/457.4 MB 3.3 MB/s eta 0:02:13
     - ------------------------------------- 22.8/457.4 MB 3.2 MB/s eta 0:02:14
     -- ------------------------------------ 23.6/457.4 MB 3.2 MB/s eta 0:02:15
     -- ------------------------------------ 24.1/457.4 MB 3.2 MB/s eta 0:02:16
     -- ------------------------------------ 24.9/457.4 MB 3.2 MB/s eta 0:02:14
     -- ------------------------------------ 25.4/457.4 MB 3.2 MB/s eta 0:02:14
     -- ------------------------------------ 26.5/457.4 MB 3.2 MB/s eta 0:02:14
     -- ------------------------------------ 27.0/457.4 MB 3.2 MB/s eta 0:02:14
     -- ------------------------------------ 28.0/457.4 MB 3.3 MB/s eta 0:02:12
     -- ------------------------------------ 29.1/457.4 MB 3.3 MB/s eta 0:02:10
     -- ------------------------------------ 29.9/457.4 MB 3.3 MB/s eta 0:02:09
     -- ------------------------------------ 30.7/457.4 MB 3.3 MB/s eta 0:02:09
     -- ------------------------------------ 31.5/457.4 MB 3.3 MB/s eta 0:02:08
     -- ------------------------------------ 31.7/457.4 MB 3.3 MB/s eta 0:02:08
     -- ------------------------------------ 32.5/457.4 MB 3.3 MB/s eta 0:02:09
     -- ------------------------------------ 33.0/457.4 MB 3.3 MB/s eta 0:02:10
     -- ------------------------------------ 33.6/457.4 MB 3.3 MB/s eta 0:02:09
     -- ------------------------------------ 34.3/457.4 MB 3.3 MB/s eta 0:02:10
     -- ------------------------------------ 34.6/457.4 MB 3.2 MB/s eta 0:02:11
     -- ------------------------------------ 35.1/457.4 MB 3.2 MB/s eta 0:02:11
     --- ----------------------------------- 35.4/457.4 MB 3.2 MB/s eta 0:02:12
     --- ----------------------------------- 35.9/457.4 MB 3.2 MB/s eta 0:02:13
     --- ----------------------------------- 36.4/457.4 MB 3.2 MB/s eta 0:02:13
     --- ----------------------------------- 37.2/457.4 MB 3.2 MB/s eta 0:02:13
     --- ----------------------------------- 38.0/457.4 MB 3.2 MB/s eta 0:02:12
     --- ----------------------------------- 39.3/457.4 MB 3.2 MB/s eta 0:02:10
     --- ----------------------------------- 40.1/457.4 MB 3.3 MB/s eta 0:02:08
     --- ----------------------------------- 41.2/457.4 MB 3.3 MB/s eta 0:02:08
     --- ----------------------------------- 41.7/457.4 MB 3.3 MB/s eta 0:02:08
     --- ----------------------------------- 42.5/457.4 MB 3.3 MB/s eta 0:02:07
     --- ----------------------------------- 43.5/457.4 MB 3.3 MB/s eta 0:02:06
     --- ----------------------------------- 44.8/457.4 MB 3.3 MB/s eta 0:02:04
     --- ----------------------------------- 45.6/457.4 MB 3.3 MB/s eta 0:02:04
     --- ----------------------------------- 46.4/457.4 MB 3.4 MB/s eta 0:02:03
     ---- ---------------------------------- 47.2/457.4 MB 3.4 MB/s eta 0:02:03
     ---- ---------------------------------- 47.7/457.4 MB 3.4 MB/s eta 0:02:02
     ---- ---------------------------------- 48.5/457.4 MB 3.4 MB/s eta 0:02:02
     ---- ---------------------------------- 49.0/457.4 MB 3.4 MB/s eta 0:02:02
     ---- ---------------------------------- 49.5/457.4 MB 3.3 MB/s eta 0:02:03
     ---- ---------------------------------- 50.6/457.4 MB 3.4 MB/s eta 0:02:02
     ---- ---------------------------------- 51.6/457.4 MB 3.4 MB/s eta 0:02:01
     ---- ---------------------------------- 52.4/457.4 MB 3.4 MB/s eta 0:02:00
     ---- ---------------------------------- 52.4/457.4 MB 3.4 MB/s eta 0:02:00
     ---- ---------------------------------- 52.4/457.4 MB 3.4 MB/s eta 0:02:00
     ---- ---------------------------------- 52.4/457.4 MB 3.4 MB/s eta 0:02:00
     ---- ---------------------------------- 52.7/457.4 MB 3.2 MB/s eta 0:02:06
     ---- ---------------------------------- 54.0/457.4 MB 3.3 MB/s eta 0:02:04
     ---- ---------------------------------- 55.1/457.4 MB 3.3 MB/s eta 0:02:03
     ---- ---------------------------------- 55.6/457.4 MB 3.3 MB/s eta 0:02:03
     ---- ---------------------------------- 56.6/457.4 MB 3.3 MB/s eta 0:02:02
     ---- ---------------------------------- 57.4/457.4 MB 3.3 MB/s eta 0:02:01
     ---- ---------------------------------- 58.2/457.4 MB 3.3 MB/s eta 0:02:01
     ----- --------------------------------- 59.0/457.4 MB 3.3 MB/s eta 0:02:01
     ----- --------------------------------- 59.5/457.4 MB 3.3 MB/s eta 0:02:01
     ----- --------------------------------- 60.3/457.4 MB 3.3 MB/s eta 0:02:00
     ----- --------------------------------- 61.3/457.4 MB 3.3 MB/s eta 0:02:00
     ----- --------------------------------- 61.9/457.4 MB 3.3 MB/s eta 0:02:00
     ----- --------------------------------- 62.9/457.4 MB 3.3 MB/s eta 0:01:59
     ----- --------------------------------- 63.7/457.4 MB 3.3 MB/s eta 0:01:58
     ----- --------------------------------- 64.5/457.4 MB 3.3 MB/s eta 0:01:58
     ----- --------------------------------- 65.5/457.4 MB 3.4 MB/s eta 0:01:57
     ----- --------------------------------- 66.3/457.4 MB 3.4 MB/s eta 0:01:57
     ----- --------------------------------- 67.1/457.4 MB 3.4 MB/s eta 0:01:56
     ----- --------------------------------- 68.2/457.4 MB 3.4 MB/s eta 0:01:56
     ----- --------------------------------- 68.9/457.4 MB 3.4 MB/s eta 0:01:55
     ----- --------------------------------- 69.7/457.4 MB 3.4 MB/s eta 0:01:55
     ------ -------------------------------- 70.5/457.4 MB 3.4 MB/s eta 0:01:54
     ------ -------------------------------- 71.3/457.4 MB 3.4 MB/s eta 0:01:54
     ------ -------------------------------- 72.1/457.4 MB 3.4 MB/s eta 0:01:54
     ------ -------------------------------- 72.6/457.4 MB 3.4 MB/s eta 0:01:54
     ------ -------------------------------- 73.7/457.4 MB 3.4 MB/s eta 0:01:53
     ------ -------------------------------- 74.4/457.4 MB 3.4 MB/s eta 0:01:53
     ------ -------------------------------- 75.2/457.4 MB 3.4 MB/s eta 0:01:52
     ------ -------------------------------- 76.3/457.4 MB 3.4 MB/s eta 0:01:51
     ------ -------------------------------- 77.1/457.4 MB 3.4 MB/s eta 0:01:51
     ------ -------------------------------- 78.1/457.4 MB 3.5 MB/s eta 0:01:50
     ------ -------------------------------- 78.9/457.4 MB 3.5 MB/s eta 0:01:50
     ------ -------------------------------- 79.7/457.4 MB 3.5 MB/s eta 0:01:50
     ------ -------------------------------- 80.5/457.4 MB 3.5 MB/s eta 0:01:49
     ------ -------------------------------- 81.3/457.4 MB 3.5 MB/s eta 0:01:49
     ------ -------------------------------- 82.1/457.4 MB 3.5 MB/s eta 0:01:49
     ------- ------------------------------- 82.8/457.4 MB 3.5 MB/s eta 0:01:48
     ------- ------------------------------- 83.6/457.4 MB 3.5 MB/s eta 0:01:48
     ------- ------------------------------- 84.7/457.4 MB 3.5 MB/s eta 0:01:48
     ------- ------------------------------- 85.2/457.4 MB 3.5 MB/s eta 0:01:48
     ------- ------------------------------- 86.0/457.4 MB 3.5 MB/s eta 0:01:47
     ------- ------------------------------- 86.8/457.4 MB 3.5 MB/s eta 0:01:47
     ------- ------------------------------- 87.6/457.4 MB 3.5 MB/s eta 0:01:47
     ------- ------------------------------- 88.1/457.4 MB 3.5 MB/s eta 0:01:47
     ------- ------------------------------- 88.9/457.4 MB 3.5 MB/s eta 0:01:46
     ------- ------------------------------- 89.7/457.4 MB 3.5 MB/s eta 0:01:46
     ------- ------------------------------- 90.4/457.4 MB 3.5 MB/s eta 0:01:46
     ------- ------------------------------- 91.2/457.4 MB 3.5 MB/s eta 0:01:45
     ------- ------------------------------- 92.0/457.4 MB 3.5 MB/s eta 0:01:45
     ------- ------------------------------- 92.8/457.4 MB 3.5 MB/s eta 0:01:45
     ------- ------------------------------- 93.6/457.4 MB 3.5 MB/s eta 0:01:45
     -------- ------------------------------ 94.4/457.4 MB 3.5 MB/s eta 0:01:44
     -------- ------------------------------ 95.2/457.4 MB 3.5 MB/s eta 0:01:44
     -------- ------------------------------ 95.9/457.4 MB 3.5 MB/s eta 0:01:44
     -------- ------------------------------ 97.0/457.4 MB 3.5 MB/s eta 0:01:43
     -------- ------------------------------ 97.8/457.4 MB 3.5 MB/s eta 0:01:43
     -------- ------------------------------ 98.6/457.4 MB 3.5 MB/s eta 0:01:43
     -------- ------------------------------ 99.4/457.4 MB 3.5 MB/s eta 0:01:42
     -------- ----------------------------- 100.1/457.4 MB 3.5 MB/s eta 0:01:42
     -------- ----------------------------- 101.2/457.4 MB 3.5 MB/s eta 0:01:42
     -------- ----------------------------- 102.2/457.4 MB 3.5 MB/s eta 0:01:41
     -------- ----------------------------- 103.0/457.4 MB 3.5 MB/s eta 0:01:41
     -------- ----------------------------- 103.8/457.4 MB 3.5 MB/s eta 0:01:40
     -------- ----------------------------- 104.9/457.4 MB 3.5 MB/s eta 0:01:40
     -------- ----------------------------- 105.6/457.4 MB 3.6 MB/s eta 0:01:39
     -------- ----------------------------- 106.7/457.4 MB 3.6 MB/s eta 0:01:39
     -------- ----------------------------- 107.5/457.4 MB 3.6 MB/s eta 0:01:39
     --------- ---------------------------- 108.5/457.4 MB 3.6 MB/s eta 0:01:38
     --------- ---------------------------- 109.3/457.4 MB 3.6 MB/s eta 0:01:38
     --------- ---------------------------- 110.1/457.4 MB 3.6 MB/s eta 0:01:38
     --------- ---------------------------- 110.9/457.4 MB 3.6 MB/s eta 0:01:38
     --------- ---------------------------- 111.7/457.4 MB 3.6 MB/s eta 0:01:37
     --------- ---------------------------- 112.7/457.4 MB 3.6 MB/s eta 0:01:36
     --------- ---------------------------- 113.2/457.4 MB 3.6 MB/s eta 0:01:36
     --------- ---------------------------- 113.8/457.4 MB 3.6 MB/s eta 0:01:36
     --------- ---------------------------- 113.8/457.4 MB 3.6 MB/s eta 0:01:36
     --------- ---------------------------- 114.0/457.4 MB 3.6 MB/s eta 0:01:37
     --------- ---------------------------- 114.3/457.4 MB 3.5 MB/s eta 0:01:37
     --------- ---------------------------- 114.3/457.4 MB 3.5 MB/s eta 0:01:37
     --------- ---------------------------- 114.6/457.4 MB 3.5 MB/s eta 0:01:39
     --------- ---------------------------- 114.6/457.4 MB 3.5 MB/s eta 0:01:39
     --------- ---------------------------- 114.8/457.4 MB 3.4 MB/s eta 0:01:40
     --------- ---------------------------- 114.8/457.4 MB 3.4 MB/s eta 0:01:40
     --------- ---------------------------- 114.8/457.4 MB 3.4 MB/s eta 0:01:40
     --------- ---------------------------- 115.1/457.4 MB 3.4 MB/s eta 0:01:42
     --------- ---------------------------- 115.3/457.4 MB 3.3 MB/s eta 0:01:43
     --------- ---------------------------- 115.9/457.4 MB 3.3 MB/s eta 0:01:43
     --------- ---------------------------- 116.1/457.4 MB 3.3 MB/s eta 0:01:43
     --------- ---------------------------- 116.7/457.4 MB 3.3 MB/s eta 0:01:43
     --------- ---------------------------- 116.9/457.4 MB 3.3 MB/s eta 0:01:43
     --------- ---------------------------- 117.4/457.4 MB 3.3 MB/s eta 0:01:43
     --------- ---------------------------- 118.2/457.4 MB 3.3 MB/s eta 0:01:43
     --------- ---------------------------- 118.8/457.4 MB 3.3 MB/s eta 0:01:42
     --------- ---------------------------- 119.3/457.4 MB 3.3 MB/s eta 0:01:42
     --------- ---------------------------- 119.8/457.4 MB 3.3 MB/s eta 0:01:43
     --------- ---------------------------- 120.1/457.4 MB 3.3 MB/s eta 0:01:43
     ---------- --------------------------- 120.6/457.4 MB 3.3 MB/s eta 0:01:42
     ---------- --------------------------- 121.1/457.4 MB 3.3 MB/s eta 0:01:42
     ---------- --------------------------- 121.6/457.4 MB 3.3 MB/s eta 0:01:42
     ---------- --------------------------- 122.2/457.4 MB 3.3 MB/s eta 0:01:42
     ---------- --------------------------- 122.4/457.4 MB 3.3 MB/s eta 0:01:42
     ---------- --------------------------- 122.9/457.4 MB 3.3 MB/s eta 0:01:42
     ---------- --------------------------- 123.5/457.4 MB 3.3 MB/s eta 0:01:42
     ---------- --------------------------- 124.0/457.4 MB 3.3 MB/s eta 0:01:42
     ---------- --------------------------- 124.5/457.4 MB 3.3 MB/s eta 0:01:42
     ---------- --------------------------- 124.8/457.4 MB 3.3 MB/s eta 0:01:43
     ---------- --------------------------- 125.3/457.4 MB 3.2 MB/s eta 0:01:43
     ---------- --------------------------- 125.8/457.4 MB 3.2 MB/s eta 0:01:44
     ---------- --------------------------- 126.4/457.4 MB 3.2 MB/s eta 0:01:44
     ---------- --------------------------- 126.6/457.4 MB 3.2 MB/s eta 0:01:44
     ---------- --------------------------- 126.9/457.4 MB 3.2 MB/s eta 0:01:45
     ---------- --------------------------- 127.7/457.4 MB 3.2 MB/s eta 0:01:44
     ---------- --------------------------- 127.9/457.4 MB 3.2 MB/s eta 0:01:44
     ---------- --------------------------- 128.5/457.4 MB 3.2 MB/s eta 0:01:44
     ---------- --------------------------- 129.0/457.4 MB 3.2 MB/s eta 0:01:44
     ---------- --------------------------- 129.2/457.4 MB 3.2 MB/s eta 0:01:44
     ---------- --------------------------- 129.8/457.4 MB 3.2 MB/s eta 0:01:44
     ---------- --------------------------- 130.5/457.4 MB 3.2 MB/s eta 0:01:43
     ---------- --------------------------- 131.6/457.4 MB 3.2 MB/s eta 0:01:42
     ----------- -------------------------- 132.6/457.4 MB 3.2 MB/s eta 0:01:41
     ----------- -------------------------- 134.0/457.4 MB 3.2 MB/s eta 0:01:40
     ----------- -------------------------- 135.0/457.4 MB 3.2 MB/s eta 0:01:40
     ----------- -------------------------- 135.8/457.4 MB 3.2 MB/s eta 0:01:40
     ----------- -------------------------- 136.8/457.4 MB 3.2 MB/s eta 0:01:39
     ----------- -------------------------- 137.9/457.4 MB 3.2 MB/s eta 0:01:39
     ----------- -------------------------- 138.9/457.4 MB 3.3 MB/s eta 0:01:38
     ----------- -------------------------- 140.0/457.4 MB 3.3 MB/s eta 0:01:38
     ----------- -------------------------- 140.8/457.4 MB 3.3 MB/s eta 0:01:38
     ----------- -------------------------- 141.8/457.4 MB 3.3 MB/s eta 0:01:37
     ----------- -------------------------- 142.6/457.4 MB 3.2 MB/s eta 0:01:37
     ----------- -------------------------- 143.7/457.4 MB 3.3 MB/s eta 0:01:37
     ------------ ------------------------- 144.7/457.4 MB 3.3 MB/s eta 0:01:36
     ------------ ------------------------- 145.8/457.4 MB 3.3 MB/s eta 0:01:36
     ------------ ------------------------- 146.8/457.4 MB 3.3 MB/s eta 0:01:35
     ------------ ------------------------- 147.8/457.4 MB 3.3 MB/s eta 0:01:34
     ------------ ------------------------- 148.6/457.4 MB 3.3 MB/s eta 0:01:34
     ------------ ------------------------- 149.4/457.4 MB 3.3 MB/s eta 0:01:33
     ------------ ------------------------- 150.2/457.4 MB 3.3 MB/s eta 0:01:33
     ------------ ------------------------- 151.0/457.4 MB 3.3 MB/s eta 0:01:33
     ------------ ------------------------- 152.0/457.4 MB 3.4 MB/s eta 0:01:31
     ------------ ------------------------- 153.1/457.4 MB 3.4 MB/s eta 0:01:30
     ------------ ------------------------- 154.1/457.4 MB 3.4 MB/s eta 0:01:29
     ------------ ------------------------- 155.2/457.4 MB 3.4 MB/s eta 0:01:29
     ------------ ------------------------- 156.0/457.4 MB 3.4 MB/s eta 0:01:29
     ------------- ------------------------ 157.0/457.4 MB 3.4 MB/s eta 0:01:28
     ------------- ------------------------ 158.1/457.4 MB 3.4 MB/s eta 0:01:28
     ------------- ------------------------ 159.1/457.4 MB 3.4 MB/s eta 0:01:27
     ------------- ------------------------ 160.2/457.4 MB 3.4 MB/s eta 0:01:27
     ------------- ------------------------ 161.0/457.4 MB 3.4 MB/s eta 0:01:27
     ------------- ------------------------ 162.3/457.4 MB 3.5 MB/s eta 0:01:26
     ------------- ------------------------ 163.3/457.4 MB 3.5 MB/s eta 0:01:25
     ------------- ------------------------ 164.4/457.4 MB 3.5 MB/s eta 0:01:25
     ------------- ------------------------ 165.4/457.4 MB 3.5 MB/s eta 0:01:24
     ------------- ------------------------ 166.7/457.4 MB 3.5 MB/s eta 0:01:24
     ------------- ------------------------ 167.8/457.4 MB 3.5 MB/s eta 0:01:23
     -------------- ----------------------- 168.8/457.4 MB 3.5 MB/s eta 0:01:23
     -------------- ----------------------- 169.9/457.4 MB 3.5 MB/s eta 0:01:22
     -------------- ----------------------- 170.9/457.4 MB 3.5 MB/s eta 0:01:22
     -------------- ----------------------- 172.0/457.4 MB 3.5 MB/s eta 0:01:21
     -------------- ----------------------- 173.0/457.4 MB 3.5 MB/s eta 0:01:21
     -------------- ----------------------- 173.5/457.4 MB 3.5 MB/s eta 0:01:21
     -------------- ----------------------- 174.6/457.4 MB 3.5 MB/s eta 0:01:21
     -------------- ----------------------- 175.4/457.4 MB 3.5 MB/s eta 0:01:20
     -------------- ----------------------- 176.4/457.4 MB 3.5 MB/s eta 0:01:20
     -------------- ----------------------- 177.5/457.4 MB 3.5 MB/s eta 0:01:20
     -------------- ----------------------- 178.5/457.4 MB 3.6 MB/s eta 0:01:19
     -------------- ----------------------- 179.6/457.4 MB 3.6 MB/s eta 0:01:18
     --------------- ---------------------- 180.9/457.4 MB 3.6 MB/s eta 0:01:18
     --------------- ---------------------- 181.7/457.4 MB 3.6 MB/s eta 0:01:18

[notice] A new release of pip is available: 24.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

# Load Model

In [3]:
def load_model():
    nlp = spacy.load("en_core_web_trf")
    return nlp

In [4]:
nlp_model = load_model()

d:\NLP Analyzer\analyzer\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Load Dataset

In [5]:
import os
import sys
import pathlib
folder_path = pathlib.Path().parent.resolve()
sys.path.append(os.path.join(folder_path, '../'))
from utils import load_subtitles_dataset

In [6]:
dataset_path = "../data/Subtitles/"
df = load_subtitles_dataset(dataset_path)

In [7]:
df.head()

   episode                                             script
0        1  A long time ago, a powerful demon fox appeared...
1        2  C'mon!\n Running like a fugitive,\n Being chas...
2        3  C'mon!\n Running like a fugitive,\n Being chas...
3        4  C'mon!\n Running like a fugitive,\n Being chas...
4        5  C'mon!\n Running like a fugitive,\n Being chas...

In [8]:
sample_script = df.iloc[1]['script']
sample_script

'C\'mon!\n Running like a fugitive,\n Being chased by something\n Inside my heart is pounding\n My throat dry like it\'s withering\n For no single one,\n To none does belong,\n This time is ours, right now...\n Unraveling the pain,\n Unraveling our hearts,\n Unraveling shadows\n Stifling our breath,\n Reaching for beyond,\n Tearing through the dark\n In fighting and in love\n To the distant light above,\n Yes, we are on the way\n I wanna rock...\n Rockin\' my heart\n Hey, you!\n Are you sure you want to look like that?\n Yes, of course! C\'mon! So hurry hurry!\n Don\'t regret it later.\n Say cheese!\n My Name Is Konohamaru!\n I couldn\'t decide on how to look.\n It took me 3 hours to decide.\n But as you can see, it\'s more like a work of art.\n Doesn\'t it look great?\n Take it over.\n What?!\n Take it over.\n Stop saying that!\n Transform!\n Oh please, Lord Hokage…\n The Sexy Jutsu… That\'s quite a devious technique.\n By the way Naruto, where\'s your headband?\n I won\'t wear it until the orientation. lt might get scratched\n Well, that\'s just fine.\n But the Ninja Registration Form is a very important document\n held in high regard by our village.\n Why do you want to look like this?\n Because!\n Anyway, how should I know about all that stuff?\n Old man! Get ready to fight!\n I am going to be the Fifth Hokage!\n Ouch!\n If it\'s not one thing, it\'s another….\n Drat! Is this a trap?\n Are you okay, Honorable Grandson?\n May I just inform you that there aren\'t any traps here…\n Huh? What\'s with this runt?\n What?!\n I know this kid… He\'s that Nine-Tailed boy!\n He\'s a good-for-nothing scoundrel!\n You must have done this to me!\n You tripped all by yourself, stupid!\n Hey! Let go of him!\n He is the Honorable Grandson of the Third Hokage!\n He stopped as soon as he learned who I am….\n He\'s like my four-eyed teacher.\n He\'s just like everyone else!\n What\'s the matter?\n Weren\'t you gonna hit me, huh?\n Can\'t do it \'cuz I\'m the Hokage\'s grandson, eh?\n As if I care! \t\t\t\t\tlmbecile!\n This guy…\n What?!\n Good grief…\n Listen to me.\n You are the Honorable Grandson of the Third Hokage.\n Even though that scoundrel hit you, you must not associate with his kind.\n Nothing good will come of your tangling with him.\n This is your distinguished teacher Ebisu,\n and I am never wrong about these things!\n Don\'t you want to become the Fifth Hokage?\n Then allow me to teach you Ninjutsu,\n so that your dream will become a reality.\n That\'s right.\n Stick with me and you will gain a shortcut towards becoming the Fifth Hokage.\n Is that clear, Honorable Grandson?\n He\'s gone!\n It seems he\'s gone after Naruto.\n Oh no!\n This is terrible!\n Honorable Grandson!\n How did he become like this?\n That was the 20th sneak attack today.\n And now he\'s in the company of Naruto. I\'m a bit worried.\n I just hope he doesn\'t pick up more foolishness.\n Huh?\n Stop following me!\n What is it now?!\n Your camouflage is pathetic.\n You\'ve seen through my disguise...\n Your reputation is well-earned.\n I will allow you to make me your apprentice.\n But you must first teach me that  "Sexy Jutsu"  technique\n you used to beat Grandpa Hokage.\n You gotta be kidding.\n I beg you to say yes, boss!\n Huh?\n Boss?\n Boss! Boss! Boss!\n I guess I have no choice.\n Listen.\n In order to become a skilled Ninja,\n you must first learn to control your Chatora.\n Chatora?\n Yes, Chatora.\n Boss, I think you mean Chakra.\n Silence!\n That\'s what real Ninjas call it!\n Oh! I didn\'t know that!\n Whew… I\'m glad he\'s a fool.\n Listen. Chakra essentially means…\n Basically, it is the energy needed in order to use Jutsu.\n Huh?\n In other words, fundamentally Ninja Arts combine the Chakra,\n the physical energy accumulated from each cell in the body\n with spiritual energy intensified through training and experience.\n This combined energy is summoned with certain hand signs.\n You made me think you knew all that,\n when you were just reading from a scroll!\n Much has been said about perfecting the Ninja techniques,\n but it really boils down to just one thing.\n And what is that?\n Hard work and guts.\n Hard work and guts?\n That\'s right.\n So be ready for the challenging tasks I will give you.\n Yes, boss!\n Good. Let\'s start right now. Transform for me.\n Huh?\n Let me see first how much you already know.\n But what do I transform into?\n OK... First, transform into that lady.\n An easy task, boss.\n Transform!\n Well, do I look like her?\n Uhm… Well, the clothes do and…\n And what\'s so similar about that?!\n Honorable Grandson.\n If you will transform into me, at least try to look a little cuter, OK?\n She\'s scary!\n Why am I the one who gets hit?\n OK! Next, we\'ll do some research on sexiness!\n Yes, boss!\n I told you I don\'t allow reading here, Naruto!\n This is the last test. Put all of your effort into it!\n Yes, boss!\n Transform!\n Naruto! It\'s you again!\n Why is it always me…?\n Sorry.\n Huh?\n It\'s because I\'m the Hokage\'s grandson.\n Don\'t worry about it.\n Huh?\n You\'re now ready to perform the Sexy Jutsu!\n You just need more practice.\n Yes, boss!\n OK, keep in mind… the point is for "boom boom boom"!\n Now do it!\n Yes, boss! \t\t\t\t\tTransform!\n What do you think?\n That won\'t do!\n More slender.\n Yes, boss!\n Is this okay?\n Not yet. \t\t\t\t\tMore attractive.\n Yes, boss!\n How about now?\n That Naruto… What is he teaching the Honorable Grandson…?\n Where the hell could they be…?\n I am a distinguished teacher training potential Hokage.\n All those who interfere will be eliminated.\n You know I\'ve been wondering…\n You seem obsessed with beating your Grandpa Hokage.\n My name is Konohamaru.\n It was Grandpa who gave me that name.\n He named me after our village.\n It should be easy for everyone here to remember.\n But nobody ever calls me by that name.\n When they see me, all they see is the grandson of Lord Hokage.\n No one sees me for who I really am.\n I can\'t stand it anymore.\n That\'s why…\n That\'s why I want the title of Lord Hokage now.\n Idiot…Who do you think will accept you, huh?\n Huh?\n You won\'t win the title that easily, you know.\n What?!\n It\'s not that simple.\n If you\'re really serious about gaining the title of Lord Hokage…\n What?\n You\'ll have to beat me first!\n Lord Hokage! I\'ve been looking for you.\n Iruka.\n Did Naruto re-submit his Ninja Registration Form?\n Yes.\n When I lectured to him the other night at the ramen stand,\n he said he will make everyone accept him now that he\'s a Ninja.\n He\'s been happy since then.\n It might not be easy for Naruto to realize that dream.\n Huh?\n As you well know,\n only the villagers who fought the Nine-Tailed Fox Spirit 12 years ago\n know that the monster is sealed inside Naruto.\n I ruled that no one shall speak about that incident.\n I have severely punished those who have broken this rule.\n Now our children know nothing about it.\n That is the only positive development for Naruto.\n Before the Fourth Hokage trapped the monster and died,\n his last wish was for the villagers to regard Naruto as a hero.\n A hero?\n The Fourth Hokage sealed the monster into the navel of a newborn baby\n whose umbilical cord had just been cut.\n As the receptacle for the Nine-Tailed Fox Spirit,\n Naruto saved the village.\n Unfortunately, the other villagers don\'t see him like that.\n Some even say that Naruto is the Nine-Tailed Fox Spirit himself.\n Little by little, that attitude has been passed down to their own children.\n Iruka. \t\t\t\t\tDo you know?\n What, sir?\n When someone is hated and people refuse to accept his existence,\n he sees it in the eyes of the people around him.\n I have found you!\n Huh?\n That Demon Fox!!\n That cold look! lt\'s always like that!\n Honorable Grandson, we have to go now.\n No way!\n I want to beat Grandpa right now so I can win the title of Lord Hokage!\n Don\'t get in my way!\n A Hokage must first know about virtue, honor, etiquette, wisdom, loyalty, faith,\n judgment, obedience and all that.\n He must be skilled at more than thousand techniques…\n And then...\n Transform!\n Take this! Sexy Jutsu!\n What? \t\t\t\t\tlt didn\'t work!\n What kind of a disgraceful spell is that?!\n I am a gentleman!\n Such vulgar attacks will never work on me!\n Honorable Grandson! That rascal will only make you an imbecile!\n Stick with me and...\n you will gain a shortcut towards becoming the Fifth Hokage.\n C\'mon, let\'s go!\n No way!\n Shadow Clone Jutsu\n Wow! \t\t\t\t\tFantastic!\n Ha! \t\t\t\t\tThat\'s nothing.\n I am a distinguished teacher.\n I am not as weak as Mizuki.\n Boss…\n Transform!\n Transform!\n Oh, Master Ebisu…\n I call it "the Harem Jutsu"!\n He combined the Multiple Clones with his own Sexy Jutsu.\n That\'s another devious attack.\n I probably won\'t even survive that one.\n I can\'t even beat that four-eyed teacher of mine!\n I want the title of Lord Hokage so badly! I want to be recognized by everybody!\n But I keep failing.\n You think it\'s that easy?\n Huh?\n It\'s given only to the greatest Ninja in the village.\n Everybody must learn to believe in you.\n I\'ve been through a lot already.\n It\'s been one struggle after another.\n But after all that, I found someone who accepts me.\n I had to go through a lot... Just for one person.\n You had better push yourself.\n For what?\n The path of getting the title, Lord Hokage, is a brutal one.\n There\'s no such thing as a shortcut.\n If you\'re really serious about attaining the title of Lord Hokage\n You\'ll have to beat me first.\n Who do you think you are, lecturing me like that?\n I won\'t be your apprentice anymore.\n From now on, you\'re my rival.\n Unfortunately for you, tomorrow I graduate from the Ninja Academy.\n Still, I\'ll consider you an equal someday when we fight for the title of Lord Hokage.\n Let\'s look forward to that, Konohamaru.\n You still have a long way to go to become a real Ninja.\n Aaah! Why do I have to be in the same group with Sasuke?\n The guy I hate the most?\n Sakura keeps saying  "Sasuke Sasuke Sasuke!"\n and doesn\'t even pay attention to me!\n It makes me so mad! I got it! I\'m going to pull one on him!\n I\'m not gonna let him be so cool in front of Sakura!\n Next Episode:  "Sasuke and Sakura: Friends or Foes?"\n Watch my outstanding performance!\n'

In [9]:
sentences = sent_tokenize(sample_script)

In [10]:
sentences = sentences[60:90]

In [11]:
sentence = ".".join(sentences)

In [12]:
sentence

'Then allow me to teach you Ninjutsu,\n so that your dream will become a reality..That\'s right..Stick with me and you will gain a shortcut towards becoming the Fifth Hokage..Is that clear, Honorable Grandson?.He\'s gone!.It seems he\'s gone after Naruto..Oh no!.This is terrible!.Honorable Grandson!.How did he become like this?.That was the 20th sneak attack today..And now he\'s in the company of Naruto..I\'m a bit worried..I just hope he doesn\'t pick up more foolishness..Huh?.Stop following me!.What is it now?!.Your camouflage is pathetic..You\'ve seen through my disguise....Your reputation is well-earned..I will allow you to make me your apprentice..But you must first teach me that  "Sexy Jutsu"  technique\n you used to beat Grandpa Hokage..You gotta be kidding..I beg you to say yes, boss!.Huh?.Boss?.Boss!.Boss!.Boss!.I guess I have no choice.'

# Run Model

In [13]:
doc = nlp_model(sentence)

In [14]:
doc.ents

(Fifth, Naruto, 20th, today, Naruto, Hokage)

In [15]:
for entity in doc.ents:
    print(entity, entity.label_)

Fifth ORDINAL
Naruto PERSON
20th ORDINAL
today DATE
Naruto PERSON
Hokage PERSON

In [59]:
def get_ners_inference(script):
    script_sentences = sent_tokenize(script)

    ner_output = []

    for sentence in script_sentences:
        doc = nlp_model(sentence)
        ners = set()
        for entity in doc.ents:
            if entity.label_ == "PERSON":
                # Clean and extract the name
                first_name = entity.text.strip().split()[0]

                # ADD IT TO THE SET (Choose first_name or entity.text)
                ners.add(first_name)

        # Convert set to list before saving if needed by downstream code
        ner_output.append(list(ners))

    return ner_output

In [60]:
df = df.head(10)
df

   episode                                             script
0        1  A long time ago, a powerful demon fox appeared...
1        2  C'mon!\n Running like a fugitive,\n Being chas...
2        3  C'mon!\n Running like a fugitive,\n Being chas...
3        4  C'mon!\n Running like a fugitive,\n Being chas...
4        5  C'mon!\n Running like a fugitive,\n Being chas...
5        6  C'mon!\n Running like a fugitive,\n Being chas...
6        7  C'mon!\n Running like a fugitive,\n Being chas...
7        8  C'mon!\n Running like a fugitive,\n Being chas...
8        9  C'mon!\n Running like a fugitive,\n Being chas...
9       12  C'mon!\n Running like a fugitive,\n Being chas...

In [61]:
df['ners'] = df['script'].apply(get_ners_inference)

In [62]:
df

,episode,script,ners
0,1,"A long time ago, a powerful demon fox appeared...","[[], [], [], [], [], [], [], [Naruto], [], [],..."
1,2,"C'mon!\n Running like a fugitive,\n Being chas...","[[], [], [], [], [], [], [], [], [], [Konohama..."
2,3,"C'mon!\n Running like a fugitive,\n Being chas...","[[], [], [], [Sasuke, Sakura], [], [Konohamaru..."
3,4,"C'mon!\n Running like a fugitive,\n Being chas...","[[], [], [], [Naruto], [], [], [Iruka], [], [N..."
4,5,"C'mon!\n Running like a fugitive,\n Being chas...","[[], [], [], [], [], [], [], [], [], [], [], [..."
5,6,"C'mon!\n Running like a fugitive,\n Being chas...","[[], [], [Sasuke], [], [Naruto], [], [Naruto],..."
6,7,"C'mon!\n Running like a fugitive,\n Being chas...","[[], [], [], [], [], [], [], [], [], [], [], [..."
7,8,"C'mon!\n Running like a fugitive,\n Being chas...","[[], [], [], [], [], [], [], [Sasuke], [], [],..."
8,9,"C'mon!\n Running like a fugitive,\n Being chas...","[[], [], [], [], [], [], [], [], [], [], [], [..."
9,12,"C'mon!\n Running like a fugitive,\n Being chas...","[[], [], [], [], [Zabuza], [], [], [], [Naruto..."

# Character Network

In [63]:
import pandas as pd
import matplotlib.pyplot as plt
import networkx as nx 
from pyvis.network import Network

In [64]:
def generate_character_network(df):

    windows=10
    entity_relationship = []

    for row in df['ners']:
        previous_entities_in_window = []

        for sentence in row:
            previous_entities_in_window.append(list(sentence))
            previous_entities_in_window = previous_entities_in_window[-windows:]

            # Flatten 2D List into 1D List
            previous_entities_flattened = sum(previous_entities_in_window, [])

            for entity in sentence:
                for entity_in_window in previous_entities_flattened:
                    if entity != entity_in_window:
                        entity_relationship.append(sorted([entity, entity_in_window]))
    
    relationship_df = pd.DataFrame({'value': entity_relationship})
    relationship_df['source'] = relationship_df['value'].apply(lambda x: x[0])
    relationship_df['target'] = relationship_df['value'].apply(lambda x: x[1])
    relationship_df = relationship_df.groupby(['source', 'target']).count().reset_index()
    relationship_df = relationship_df.sort_values('value', ascending=False)

    return relationship_df

In [65]:
relationship_df = generate_character_network(df)

In [66]:
relationship_df

      source     target  value
164   Naruto     Sasuke    122
203   Sakura     Sasuke     69
90     Iruka     Naruto     45
163   Naruto     Sakura     40
155   Mizuki     Naruto     29
..       ...        ...    ...
179  Narutos      jonin      1
86       Ino     Sasuke      1
38     Genin     Naruto      1
39     Genin      Ninja      1
134     Kiba  Shikamaru      1

[268 rows x 3 columns]

In [67]:
relationship_df = relationship_df.sort_values('value', ascending=False)
relationship_df = relationship_df.head(200)

In [68]:
G = nx.from_pandas_edgelist(
    relationship_df,
    source='source',
    target='target',
    edge_attr='value',
    create_using=nx.Graph()
)

net = Network(notebook=True, width="1000px", height="700px", bgcolor="#222222", font_color="white", cdn_resources="remote")
node_degree = dict(G.degree)
nx.set_node_attributes(G, node_degree, 'size')
net.from_nx(G)
net.show("naruto.html")

naruto.html