In [46]:
from transformers import pipeline
from nltk import sent_tokenize
import nltk
import torch
from glob import glob
import pandas as pd
import numpy as np

In [2]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

# Load Model

In [4]:
model_name = "cross-encoder/nli-deberta-v3-small"
device = 0 if torch.cuda.is_available() else 'cpu'

In [5]:
device

'cpu'

In [6]:
def load_model(device):
    theme_classifier = pipeline(
        "zero-shot-classification",
        model=model_name,
        device=device
    )

    return theme_classifier

In [7]:
theme_classifier = load_model(device)

d:\NLP Analyzer\analyzer\Lib\site-packages\huggingface_hub\file_download.py:159: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\hp\.cache\huggingface\hub\models--cross-encoder--nli-deberta-v3-small. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Error while downloading from https://cas-bridge.xethub.hf.co/xet-bridge-us/621ffdc136468d709f17a21a/3a9c57043e195d65bc3a07e5280c6aec6a448892a603fd02ecdbfd9ce3cdb3e4?Expires=1783867106&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jYXMtYnJpZGdlLnhldGh1Yi5oZi5jby94ZXQtYnJpZGdlLXVzLzYyMWZmZGMxMzY0NjhkNzA5ZjE3YTIxYS8zYTljNTcwNDNlMTk1ZDY1YmMzYTA3ZTUyODBjNmFlYzZhNDQ4ODkyYTYwM2ZkMDJlY2RiZmQ5Y2UzY2RiM2U0KiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTc4Mzg2NzEwNn19fV19&Signature=MEUCIQDMLsjSE4PPWvLBA4NJ0%7EFcTBfAun6a0rrJUDfavY493AIgcnUjem1nJzr0LhiD9VNO3BaxzRaZxFbJg9%7EOb69FTz4_&Key-Pair-Id=K1LYXO563TGWFU&X-Xet-Cas-Uid=67c7224ac323ec211eedc800&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=cas%2F20260712%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20260712T133826Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=c3c9b550d7524e5742387acfb37060ccdb3c7fb329272cc1e6f3dcc36460b3f4: HTTPSConnectionPool(host='cas-bridge.xethub.hf.co', port=443): Read timed out.
Trying to resume download...

In [8]:
theme_list = ["friendship","hope","sacrifice","battle","self development","betrayal","love","dialogue"]

In [9]:
theme_classifier(
    "I gave him a right hook and left jab",
    theme_list,
    multi_label = True
)

{'sequence': 'I gave him a right hook and left jab',
 'labels': ['dialogue',
  'battle',
  'betrayal',
  'sacrifice',
  'hope',
  'friendship',
  'self development',
  'love'],
 'scores': [0.9745749235153198,
  0.897918164730072,
  0.20123253762722015,
  0.05430277809500694,
  0.04668775573372841,
  0.0038101125974208117,
  0.0019013064447790384,
  0.00013688467151951045]}

# Load Dataset

In [11]:
files = glob('../data/Subtitles/*.ass')

In [12]:
files[:5]

['../data/Subtitles\\Naruto Season 1 - 01.ass',
 '../data/Subtitles\\Naruto Season 1 - 02.ass',
 '../data/Subtitles\\Naruto Season 1 - 03.ass',
 '../data/Subtitles\\Naruto Season 1 - 04.ass',
 '../data/Subtitles\\Naruto Season 1 - 05.ass']

In [13]:
with open(files[0], 'r') as file:
    lines = file.readlines()
    lines = lines[27:]
    lines = [",".join(line.split(',')[9:]) for line in lines]

In [14]:
lines[:5]

['A long time ago, a powerful demon fox\\Nappeared with nine tails.\n',
 'With its powerful tails,\n',
 'it could smash mountains\\Nand create tidal waves.\n',
 'A band of Ninjas rose to\\Ndefend their village from attack.\n',
 'We have to wait until\\Nthe Fourth Hokage gets here!\n']

In [15]:
lines = [line.replace('\\N', " ") for line in lines]
lines[:2]

['A long time ago, a powerful demon fox appeared with nine tails.\n',
 'With its powerful tails,\n']

In [16]:
" ".join(lines[:10])

"A long time ago, a powerful demon fox appeared with nine tails.\n With its powerful tails,\n it could smash mountains and create tidal waves.\n A band of Ninjas rose to defend their village from attack.\n We have to wait until the Fourth Hokage gets here!\n We can't let it get any closer to our village!\n One great Ninja was able to imprison the monster,\n but died in the process.\n This Ninja was known asâ€¦ the Fourth Hokage.\n Naruto!\n"

In [17]:
int(files[0].split('-')[-1].split('.')[0].strip())

1

In [27]:
def load_subtitles_dataset(dataset_path):
    subtitles_paths = glob(dataset_path+'/*.ass')

    scripts=[]
    episode_num=[]

    for path in subtitles_paths:

        #Read Lines
        with open(path,'r', encoding='utf-8') as file:
            lines = file.readlines()
            lines = lines[27:]
            lines =  [ ",".join(line.split(',')[9:])  for line in lines ]
        
        lines = [ line.replace('\\N',' ') for line in lines]
        script = " ".join(lines)

        episode = int(path.split('-')[-1].split('.')[0].strip())

        scripts.append(script)
        episode_num.append(episode)

    df = pd.DataFrame.from_dict({"episode":episode_num, "script":scripts })
    return df

In [28]:
dataset_path = "../data/Subtitles"
df = load_subtitles_dataset(dataset_path)

In [29]:
df.head()

   episode                                             script
0        1  A long time ago, a powerful demon fox appeared...
1        2  C'mon!\n Running like a fugitive,\n Being chas...
2        3  C'mon!\n Running like a fugitive,\n Being chas...
3        4  C'mon!\n Running like a fugitive,\n Being chas...
4        5  C'mon!\n Running like a fugitive,\n Being chas...

# Run Model

In [31]:
script = df.iloc[0]['script']
script

'A long time ago, a powerful demon fox appeared with nine tails.\n With its powerful tails,\n it could smash mountains and create tidal waves.\n A band of Ninjas rose to defend their village from attack.\n We have to wait until the Fourth Hokage gets here!\n We can\'t let it get any closer to our village!\n One great Ninja was able to imprison the monster,\n but died in the process.\n This Ninja was known as… the Fourth Hokage.\n Naruto!\n Why did you do such a thing?!\n You\'re really gonna get it this time!\n I don\'t care!\n You know your problem?\n You can\'t do the things I do!\n Only I can do this!\n I\'m better than all of you! Believe it!\n There\'s a problem, sir!\n Lord Hokage!\n What is it?\n Did that Naruto do something again?\n Yes. He climbed onto the Mountainside Images…\n And he vandalized and graffitied all over them!\n Wait!\n Ha ha…\n Why should I?\n Hey, Naruto!\n How did you suddenly get here, lruka Sensei?\n The question is what are you doing here when you should be in class now?\n Now listen, Naruto.\n You failed the last graduation test and the one before that.\n This is no time to be goofing off, you fool!\n We will have a re-test on the Transformation Jutsu!\n Even those who already passed will take it!\n Whaaaat?!\n Sakura Haruno. Here I go…\n Transform!\n OK!\n I did it!\n Cha!\n Did you see that, Sasuke?\n Next, Sasuke Uchiha.\n Yes.\n O-OK.\n Next, Naruto Uzumaki.\n This is a real pain.\n And it\'s all your fault.\n Like I care!!\n OK…\n Good luck, Naruto…\n Transform!\n How was it?\n I call it the "Sexy Jutsu"!\n You fool! Stop making idiotic spells!\n Darn…\n Darn…\n I won\'t let you go home unless you clean that all up.\n I don\'t care…\n There\'s nobody home anyway.\n Naruto...\n What is it this time?\n What I meant was…\n If you clean up all that mess, I\'ll buy you ramen tonight.\n Huh?!\n Yes! I-I will finish it no time!\n Enter: Naruto Uzumaki!\n Naruto.\n Why did you vandalize those faces?\n Don\'t you know who the Hokage leaders are?\n Of course, I do!\n I know they earned the title Lord Hokage\n because they were the best Ninja of their time, right?\n Especially the Fourth Hokage was a hero\n who saved the village from the nine-tail demon fox.\n Then why did you do that?\n Because I\'ll become a Hokage myself.\n And I\'ll be the greatest Hokage of all time!\n So that everyone will finally learn to accept me!\n By the way, Sensei, I have a favor to ask.\n You want another bowl?\n Mmmm…No…\n Can I borrow that Leaf headband for a while?\n This?\n No no!\n This is worn only by those who have graduated from Ninja Academy.\n Tomorrow, you will…\n You\'re so mean!\n So that\'s why you took off your goggles…\n Humph... One more bowl please!\n We are now about to begin the graduation test.\n When your name is called, proceed to the next classroom.\n The test is on the Clone Jutsu.\n Oh no…\n Of all the…! That is my weakest Jutsu!\n But still… I will do it no matter what!\n Clone Jutsu!\n Disqualified!\n Iruka Sensei.\n His physical coordination and stamina are excellent.\n And he managed to come up with something.\n Isn\'t that enough for him to pass?\n Mizuki Sensei... All the others created three or more clones.\n Naruto created just one.\n And it\'s practically useless. I can\'t give him a passing mark.\n I \'m a Ninja now!\n You did well. That\'s my son.\n Congratulations for your graduation.\n I\'ll cook something good tonight!\n Look at that one.\n It\'s that boy. I hear he\'s the only one who failed.\n Serves him right.\n Imagine what would happen if he became a Ninja.\n Isn\'t that the boy who is actually…\n Hey! We\'re not supposed to talk about that.\n Iruka. We need to talk later.\n Yes, sir.\n Iruka Sensei isn\'t trying to be mean to you.\n Then why only me?\n He wants you to become strong from the bottom of his heart.\n You both don\'t have parents.\n But I really wanted to graduate.\n Heh... I guess I have no choice…\n I\'ll let you in on a big secret.\n Secret?\n Iruka.\n What is it, Lord Hokage?\n I know how you feel. But…\n Naruto also grew up without knowing the love of his parents…like you.\n Let me go!\n My mom and dad are still out there fighting!\n Wake up, Iruka Sensei!\n What\'s the matter?\n Come to Lord Hokage\'s immediately!\n I heard that Naruto… stole the Scroll of Sealing.\n The Scroll of Sealing?!\n Let\'s see…\n The first Jutsu is… Multi-Shadow Clone Jutsu?\n What?! Already a Jutsu I\'m no good at?\n Lord Hokage! We can\'t forgive him!\n This is not just a prank!\n The Scroll is a dangerous item that the First Hokage sealed!\n Depending on its use…\n It will be a major disaster if it is taken out of the village!\n Yes. Bring Naruto here at once!\n Yes, sir!\n Where did you go…Naruto?\n I will tell everyone in the village about this and eliminate Naruto…\n Then the Scroll of Sealing will be mine!\n Hey you, Naruto!\n You found me..\n And I\'ve only learned one Jutsu.\n He\'s been practicing the Jutsu…\n until he\'s become this exhausted and dirty…?\n Listen, listen! I\'m gonna show you this amazing Jutsu!\n You\'re gonna let me graduate if I can do it!\n Isn\'t it true that I can graduate if I can do one of the Jutsu written here?\n Who told you that?\n Mizuki Sensei. He told me about this scroll, and this place…\n Mizuki did?!\n I\'m impressed you found this place.\n I see now…how it is.\n Naruto, give me that scroll.\n Wait, wait… What\'s going on here?\n Naruto! Never give him that scroll!\n It is a dangerous object that contains forbidden Ninja Jutsu. It was sealed.\n Mizuki used you in order to get it for himself!\n W-Wha--?\n Naruto, Iruka is only afraid of you holding that scroll!\n Huh?\n What are you saying, Mizuki! Don\'t let him fool you, Naruto!\n I will tell you the truth.\n Idiot! Don\'t do that!\n After an incident 12 years ago, a rule was created.\n A rule?\n That is, Naruto, a rule everybody but you knows.\n Except me?! \t\t\t\t\tWhat is it?\n Stop it, Mizuki!\n The rule forbids anyone from revealing that you are actually the Demon Fox Spirit!\n Huh?\n You are actually the Demon, Nine-Tailed Fox Spirit,\n who killed Iruka\'s parents and destroyed our village!\n Stop it!\n Everyone has been deceiving you ever since.\n Didn\'t you find it strange?\n Why everyone hated you so much?\n No! No! No! No! No!\n Naruto…\n Nobody accepts you. That\'s why Iruka hates you so much!\n Iruka... Naruto grew up without the love of parents.\n Everyone avoids him like the plague after what happened.\n That\'s why he keeps misbehaving.\n It\'s the only way for him to get any attention or acknowledgement.\n He pretends to be tough, but inside he is really hurting.\n Die, Naruto!\n Naruto! \t\t\t\t\tGet down!\n Why…?\n Because you and I are the same.\n After my parents died,\n nobody paid attention to me or gave me any support.\n I wasn\'t a good student in school.\n I was the class clown… because I wanted people to notice me.\n I couldn\'t get noticed through excellence, so I kept doing stupid things.\n It was so hard.\n Isn\'t that right, Naruto?\n You felt so lonely…right? And you suffered inside, right?\n I\'m sorry, Naruto….\n If I had been more responsible, maybe you wouldn\'t have suffered so much.\n Don\'t make me laugh!\n Iruka has always hated you, ever since you killed his parents!\n He\'s just saying all that to get the Scroll of Sealing back!\n Naruto!\n Narutoooooo!\n He is not the type of kid who will change his mind.\n He will take revenge against our village using that scroll!\n Didn\'t you see his eyes? Those are the eyes of a Demon Fox.\n No… Naruto…isn\'t…like that at all!\n All I want is to kill Naruto and get the scroll.\n I\'ll take care of you later!\n I-I won\'t let you…\n Well, well.\n Mizuki has a big mouth!\n Naruto feels worse than he\'s ever felt.\n He might unleash the power locked up inside him.\n The Scroll of Sealing is now with him.\n There\'s a slight chance he might actually release\n the Nine-Tailed Fox Spirit sealed inside him!\n If that happens…\n I\'ve found him!\n Naruto!\n Everything that Mizuki said was a lie!\n Give me that scroll, quick! Mizuki is after the scroll!\n It can\'t be…\n Why is it, Naruto?\n How…\n did you know I wasn\'t Iruka…?\n Because I\'m Iruka.\n I see.\n What\'s in it for you to protect the one who killed your family?\n I\'m not gonna let a stupid idiot like you get that scroll!\n You\'re the idiot. Naruto is the same as me.\n Same?\n Anyone can do whatever he wants once he has the scroll.\n There is no way that that monster…\n that Fox Spirit, won\'t take advantage of the power of that scroll!\n You\'re right…\n I guess it was true all along!\n See, Iruka Sensei never really cared for me at all!\n ...if he was the Demon Fox Spirit.\n But Naruto is different!\n I know that he is an exceptional student.\n He works very hard,\n and he\'s single-minded and clumsy at the same time.\n No one accepts him, but he knows the meaning of human suffering.\n He is not the Demon Fox Spirit.\n He\'s Naruto Uzumaki of the Village Hidden in the Leaves!\n You are so gullible. \t\t\t\t\tlruka!\n I was gonna take you down later, but I have changed my mind.\n Die!\n I guess this is the end for me…\n Naruto?!\n You surprised me there, freak.\n If you ever lay a hand on Iruka Sensei, I\'ll kill you!\n Shut up! I can take care of a kid like you with a single blow!\n Why don\'t you try then? I\'ll strike you back a thousand-fold!\n Let\'s see you try! Show me what you can do, Demon Fox!\n Shadow Clone Jutsu!\n Naruto! You\'ve…\n Those aren\'t just images but actual clones! That\'s an advanced Ninjutsu!\n What\'s this…?\n What\'s the matter? \t\t\t\t\tC\'mon!\n Weren\'t you gonna get me with one blow? Here!\n In that case… I\'ll come to you.\n I kinda got carried away. lruka Sensei, are you okay?\n Yeah.\n He\'s really something.\n Maybe it is true.\n Maybe he will surpass all the Hokage leaders…\n Naruto, come over here. I\'d like to give you something.\n Has anyone found Naruto yet?\n No.\n Darn, this is going to be bad…\n There\'s no need to worry anymore.\n Lord Hokage!\n He\'ll be back soon.\n Sensei, how much longer?\n OK, you may open your eyes now.\n Congratulations…on your graduation.\n In celebration, we\'ll have ramen tonight!\n Iruka Sensei!\n That hurts!\n Naruto…\n I was going to lecture to you...\n that the road gets more difficult now that you\'re a Ninja.\n But I guess I\'ll just wait to tell you that until we get to the ramen stand…\n W-What do you want, you little shrimp? Quit following me!\n You\'re smaller than me and\n you\'re saying that you\'re gonna become the Fifth Hokage?\n I don\'t care if you are the 3rd Hokage\'s grandson or not.\n It\'s not that easy to be a Hokage!\n If you want it that bad, you\'re gonna have to beat me first!\n Next episode:  "My Name Is Konohamaru!"\n Watch my outstanding performance!\n'

In [32]:
script_sentences = sent_tokenize(script)
script_sentences[:3]

['A long time ago, a powerful demon fox appeared with nine tails.',
 'With its powerful tails,\n it could smash mountains and create tidal waves.',
 'A band of Ninjas rose to defend their village from attack.']

In [35]:
# Batch Sentences
sentence_batch_size = 20
script_batches = []
for index in range(0, len(script_sentences), sentence_batch_size):
    sent = " ".join(script_sentences[index: index + sentence_batch_size])
    script_batches.append(sent)

In [36]:
script_batches[:2]

["A long time ago, a powerful demon fox appeared with nine tails. With its powerful tails,\n it could smash mountains and create tidal waves. A band of Ninjas rose to defend their village from attack. We have to wait until the Fourth Hokage gets here! We can't let it get any closer to our village! One great Ninja was able to imprison the monster,\n but died in the process. This Ninja was known as… the Fourth Hokage. Naruto! Why did you do such a thing?! You're really gonna get it this time! I don't care! You know your problem? You can't do the things I do! Only I can do this! I'm better than all of you! Believe it! There's a problem, sir! Lord Hokage! What is it? Did that Naruto do something again?",
 'Yes. He climbed onto the Mountainside Images…\n And he vandalized and graffitied all over them! Wait! Ha ha…\n Why should I? Hey, Naruto! How did you suddenly get here, lruka Sensei? The question is what are you doing here when you should be in class now? Now listen, Naruto. You failed the last graduation test and the one before that. This is no time to be goofing off, you fool! We will have a re-test on the Transformation Jutsu! Even those who already passed will take it! Whaaaat?! Sakura Haruno. Here I go…\n Transform! OK! I did it! Cha! Did you see that, Sasuke? Next, Sasuke Uchiha.']

In [37]:
theme_output = theme_classifier(
    script_batches[:2],
    theme_list,
    multi_label = True
)

In [38]:
theme_output

[{'sequence': "A long time ago, a powerful demon fox appeared with nine tails. With its powerful tails,\n it could smash mountains and create tidal waves. A band of Ninjas rose to defend their village from attack. We have to wait until the Fourth Hokage gets here! We can't let it get any closer to our village! One great Ninja was able to imprison the monster,\n but died in the process. This Ninja was known as… the Fourth Hokage. Naruto! Why did you do such a thing?! You're really gonna get it this time! I don't care! You know your problem? You can't do the things I do! Only I can do this! I'm better than all of you! Believe it! There's a problem, sir! Lord Hokage! What is it? Did that Naruto do something again?",
  'labels': ['dialogue',
   'battle',
   'betrayal',
   'sacrifice',
   'hope',
   'self development',
   'friendship',
   'love'],
  'scores': [0.35116589069366455,
   0.2773132026195526,
   0.13305868208408356,
   0.03888186812400818,
   0.0010989708825945854,
   0.000769004924222827,
   0.0005422098911367357,
   0.00012130071263527498]},
 {'sequence': 'Yes. He climbed onto the Mountainside Images…\n And he vandalized and graffitied all over them! Wait! Ha ha…\n Why should I? Hey, Naruto! How did you suddenly get here, lruka Sensei? The question is what are you doing here when you should be in class now? Now listen, Naruto. You failed the last graduation test and the one before that. This is no time to be goofing off, you fool! We will have a re-test on the Transformation Jutsu! Even those who already passed will take it! Whaaaat?! Sakura Haruno. Here I go…\n Transform! OK! I did it! Cha! Did you see that, Sasuke? Next, Sasuke Uchiha.',
  'labels': ['dialogue',
   'battle',
   'betrayal',
   'self development',
   'sacrifice',
   'friendship',
   'hope',
   'love'],
  'scores': [0.5083410739898682,
   0.361782044172287,
   0.28711962699890137,
   0.22668205201625824,
   0.0691109150648117,
   0.03341829031705856,
   0.028432030230760574,
   7.522632222389802e-05]}]

In [40]:
# Wrangle Output
# battle: [0.584454848, 0.248454]
themes = {}
for output in theme_output:
    for label, score in zip(output['labels'], output['scores']):
        if label not in themes:
            themes[label] = []
        themes[label].append(score)

In [41]:
themes

{'dialogue': [0.35116589069366455, 0.5083410739898682],
 'battle': [0.2773132026195526, 0.361782044172287],
 'betrayal': [0.13305868208408356, 0.28711962699890137],
 'sacrifice': [0.03888186812400818, 0.0691109150648117],
 'hope': [0.0010989708825945854, 0.028432030230760574],
 'self development': [0.000769004924222827, 0.22668205201625824],
 'friendship': [0.0005422098911367357, 0.03341829031705856],
 'love': [0.00012130071263527498, 7.522632222389802e-05]}

In [47]:
def get_themes_inference(script):
    script_sentences = sent_tokenize(script)

    # Batch Sentence
    sentence_batch_size=20
    script_batches = []
    for index in range(0,len(script_sentences),sentence_batch_size):
        sent = " ".join(script_sentences[index:index+sentence_batch_size])
        script_batches.append(sent)
    
    # Run Model
    theme_output = theme_classifier(
        script_batches[:2],
        theme_list,
        multi_label=True
    )

    # Wrangle Output 
    themes = {}
    for output in theme_output:
        for label,score in zip(output['labels'],output['scores']):
            if label not in themes:
                themes[label] = []
            themes[label].append(score)

    themes = {key: np.mean(np.array(value)) for key,value in themes.items()}

    return themes

In [48]:

df = df.head(2)

In [49]:
df

   episode                                             script
0        1  A long time ago, a powerful demon fox appeared...
1        2  C'mon!\n Running like a fugitive,\n Being chas...

In [50]:
output_themes = df['script'].apply(get_themes_inference)

In [51]:
output_themes

0    {'dialogue': 0.42975348234176636, 'battle': 0....
1    {'betrayal': 0.42703600227832794, 'battle': 0....
Name: script, dtype: object

In [52]:
theme_df = pd.DataFrame(output_themes.tolist())

In [53]:
theme_df

,dialogue,battle,betrayal,sacrifice,hope,self development,friendship,love
0,0.429753,0.319548,0.210089,0.053996,0.014766,0.113726,0.016980,0.000098
1,0.002990,0.272796,0.427036,0.000887,0.000208,0.019527,0.000334,0.044004

In [54]:
df

   episode                                             script
0        1  A long time ago, a powerful demon fox appeared...
1        2  C'mon!\n Running like a fugitive,\n Being chas...

In [55]:
df[theme_df.columns] = theme_df
df

C:\Users\hp\AppData\Local\Temp\ipykernel_14120\3417989627.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[theme_df.columns] = theme_df
C:\Users\hp\AppData\Local\Temp\ipykernel_14120\3417989627.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[theme_df.columns] = theme_df
C:\Users\hp\AppData\Local\Temp\ipykernel_14120\3417989627.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[theme_df.columns] = theme_df
C:\Users\hp\AppData\Local\Temp\ipykernel_14120\3417989627.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[theme_df.columns] = theme_df
C:\Users\hp\AppData\Local\Temp\ipykernel_14120\3417989627.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[theme_df.columns] = theme_df
C:\Users\hp\AppData\Local\Temp\ipykernel_14120\3417989627.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[theme_df.columns] = theme_df
C:\Users\hp\AppData\Local\Temp\ipykernel_14120\3417989627.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[theme_df.columns] = theme_df
C:\Users\hp\AppData\Local\Temp\ipykernel_14120\3417989627.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[theme_df.columns] = theme_df

,episode,script,dialogue,battle,betrayal,sacrifice,hope,self development,friendship,love
0,1,"A long time ago, a powerful demon fox appeared...",0.429753,0.319548,0.210089,0.053996,0.014766,0.113726,0.016980,0.000098
1,2,"C'mon!\n Running like a fugitive,\n Being chas...",0.002990,0.272796,0.427036,0.000887,0.000208,0.019527,0.000334,0.044004

# Visualize output

In [ ]:
df = df.drop('dialogue', axis=1)

In [ ]:
df

In [ ]:
theme_output = df.drop(['episode','script'],axis=1).sum().reset_index()
theme_output.columns = ['theme','score']
theme_output

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
sns.barplot(data = theme_output ,x="theme",y="score" )
plt.xticks(rotation=45)
plt.show()